### ISSUE TITLE
kostya-sigar build failure 

### ISSUE THREAD

**Issue by zcater** [kostya/sigar#2]
Hello.
I come here from trying to update diaspora. I have little to no knowledge with ruby stuff so please excuse any wrong assumptions.

I tried both 2.0.0 and 2.0.2 and the build fails.

Here are the build logs: [2.0.0](https://paste.pound-python.org/raw/BJe9tb2dahDvXwsRI2OB/) and [2.0.2](https://paste.pound-python.org/raw/x8SvMxiTOnFy2vZjgcYp/)

**Comment by kostya** [comment]
hm, what is your os, ruby version, i just ok install it on ruby 2.3.1.
`gem install sigar` also failed?

**Comment by zcater** [comment]
Sorry, I should've posted these from the beginning.

I'm on Gentoo with glibc-2.26, gcc-6.4.0, ruby-2.3.7.

**Comment by zcater** [comment]
Trying to build sigar seems to have the same issues.

[Build log for gem install sigar](https://paste.pound-python.org/raw/3xwZCe3QH2iqs3BhAcRE/)

**Comment by kostya** [comment]
seems you have no functions `major` and `minor` in stdlibs.

i find in my /usr/include/sys/types.h this functions:
```
static inline __int32_t  major(__uint32_t _x)
{
  return (__int32_t)(((__uint32_t)_x >> 24) & 0xff);
}

static inline __int32_t  minor(__uint32_t _x)
{
  return (__int32_t)((_x) & 0xffffff);
}
```

can you try git clone this rep, then `rake build`, then add this functions or from http://unix.superglobalmegacorp.com/Net2/newsrc/sys/types.h.html, to linux_sigar.c and `rake build` again.

**Comment by zcater** [comment]
That file is from glibc.

From a quick google search it seems a common issue with glibc-2.26.

For example in https://jira.mongodb.org/browse/SERVER-29855 they seem to be recommending to also include sys/sysmacros.h.

**Comment by kostya** [comment]
so if you include `sys/sysmacros.h` in linux_sigar.c, this is fixed?

**Comment by zcater** [comment]
[This is the build log](https://paste.pound-python.org/raw/9bDnazMB6habIitclpjA/) for rake build of this repo after I added `sys/sysmacros.h`.

Looks ok-ish to me.

**Comment by kostya** [comment]
i push gem kostya-sigar 2.0.3.test, can you test it. using solutions from this https://wiki.gentoo.org/wiki/Glibc_2.26_porting_notes/sysmacros.h.

**Comment by zcater** [comment]
Unfortunately it's still not building. [The log](https://paste.pound-python.org/raw/Cc04C7UL7umTtA22XkiD/) looks the same with 2.0.3.test.

**Comment by kostya** [comment]
this is strange because i just add this fix https://wiki.gentoo.org/wiki/Glibc_2.26_porting_notes/sysmacros.h

**Comment by kostya** [comment]
https://github.com/kostya/sigar/commit/507640940ff90095b2623c560d1166788b9d140b

**Comment by kostya** [comment]
i think i fix it in 2.0.4

**Comment by zcater** [comment]
It works. Thank you!
